### ISSUE TITLE
[Documentation]: Broken links on README.md

### ISSUE THREAD

**Issue by pguthrey** [ROCmSoftwarePlatform/hipSOLVER#271]
### Description of errors

README.md has broken links, specifically "For a complete listing of all supported functions, see the [hipSOLVER user guide](https://rocm.docs.amd.com/projects/hipSOLVER/en/latest/userguide/index.html) and/or [API documentation](https://rocm.docs.amd.com/projects/hipSOLVER/en/latest/api/index.html)."

**Comment by pguthrey** [comment]
Also to rocSOLVER API at https://rocm.docs.amd.com/projects/hipSOLVER/en/latest/reference/api/index.html#library-api

**Comment by cgmb** [comment]
This content has moved to improve consistency of the documentation between the various ROCm libraries, but it seems we forgot to update the links in the README. We'll have to fix that.

I wonder if @ROCm/rocm-documentation could also add [redirects for the moved pages](https://docs.readthedocs.io/en/stable/user-defined-redirects.html). I'm sure there are probably other sites on the internet that have linked to the hipSOLVER documentation, and we cannot update them all.

**Comment by peterjunpark** [comment]
Hi, thanks for pointing this out. Redirects for those pages have been added to Read the Docs.

**Comment by cgmb** [comment]
Fixed in #273.
