### ISSUE TITLE
wrong check if environment variable HIP_PATH is defined

### ISSUE THREAD

**Issue by jakub329homola** [ROCmSoftwarePlatform/hipSOLVER#40]
in the root CMakeLists.txt, currently in the develop branch on lines 58--62, the HIP_PATH cmake variable is (supposed to be) set depending on the HIP_PATH environment variable:
```
if( NOT DEFINED $ENV{HIP_PATH})
    set( HIP_PATH "/opt/rocm/hip" )
else( )
    set (HIP_PATH $ENV{HIP_PATH} )
endif( )
```
but this is the wrong way of checking if an environment variable is defined. See
[https://cmake.org/cmake/help/latest/variable/ENV.html](https://cmake.org/cmake/help/latest/variable/ENV.html)
or
[https://cmake.org/pipermail/cmake/2011-October/046706.html](https://cmake.org/pipermail/cmake/2011-October/046706.html)

the correct way is
```
if( NOT DEFINED ENV{HIP_PATH})
    set( HIP_PATH "/opt/rocm/hip" )
else( )
    set (HIP_PATH $ENV{HIP_PATH} )
endif( )
```
(note the missing dollar in the if)

the consequence of this bug is that building hipSOLVER is not as straightforward as executing `cmake ..` and `make` when HIP is installed in a non-default location
The workaround seems to be adding an additional flag `-DCMAKE_MODULE_PATH="${HIP_PATH}/cmake"` to cmake

**Comment by cgmb** [comment]
Thank you for the defect report.

@daineAMD, this error also affects hipBLAS.

**Comment by cgmb** [comment]
I believe another possible workaround would be to also set `hip_DIR` wherever you're setting `HIP_PATH`.

Other libraries like rocBLAS and rocSOLVER don't try to do anything with `HIP_PATH` at all. Do they build in the way that you expect?

**Comment by jakub329homola** [comment]
My main machine has nvidia-gpu so I did not test the roc* libraries there at all (forgot to mention I also passed the `-DUSE_CUDA=TRUE` option to cmake).

On my amd-gpu machine I did have problems with building rocBLAS, but unfortunately don't remember the details. In the end I had to install rocBLAS using apt-get. rocSOLVER build worked as expected.

**Comment by cgmb** [comment]
As far as I can tell, the code in hipSOLVER that checks and sets the `HIP_PATH`  is redundant. [`find_package(HIP ...)` already considers the `HIP_PATH` environment variable and `/opt/rocm/hip`](https://github.com/ROCm-Developer-Tools/HIP/blob/rocm-4.3.0/cmake/FindHIP.cmake#L58-L68).

If you can delete the troublesome if/else entirely and hipSOLVER builds as expected, I think that's the best solution.

> I also passed the -DUSE_CUDA=TRUE option to cmake

In that case, the workaround I mentioned may be `HIP_DIR` (uppercase, rather than lowercase).

**Comment by jakub329homola** [comment]
Setting `hip_DIR` nor `HIP_DIR` did not help in my case.

Deleting the whole if/else did not help either. The error

```
CMake Error at CMakeLists.txt:98 (find_package):
  No "FindHIP.cmake" found in CMAKE_MODULE_PATH.
```

still persists.

**Comment by cgmb** [comment]
Interesting. Thank your for checking. Your help in this has saved a lot of time.

One last question for you: do hipFFT or hipSPARSE build as expected? They do not do anything with `HIP_PATH` at all—at least, not directly. Whatever fix we apply, I'd like to ensure that the behaviour is consistent and correct across hip{BLAS,SOLVER,FFT,SPARSE,CUB}.

**Comment by jakub329homola** [comment]
CMake-ing hipSPARSE (current branch develop) using just `cmake -DBUILD_CUDA=ON ..` fails, coult not find amd_comgr (I think amd_comgr should not be needed on nvidia platform). The whole error message:
```
CMake Error at /home/jakub/apps/cmake-3.20.5/share/cmake-3.20/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  By not providing "Findamd_comgr.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "amd_comgr", but CMake did not find one.

  Could not find a package configuration file provided by "amd_comgr" with
  any of the following names:

    amd_comgrConfig.cmake
    amd_comgr-config.cmake

  Add the installation prefix of "amd_comgr" to CMAKE_PREFIX_PATH or set
  "amd_comgr_DIR" to a directory containing one of the above files.  If
  "amd_comgr" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  /home/jakub/apps/HIP/installation/lib/cmake/hip/hip-config.cmake:155 (find_dependency)
  cmake/Dependencies.cmake:30 (find_package)
  CMakeLists.txt:98 (include)
```
Setting the `-DCMAKE_MODULE_PATH="${HIP_PATH}/cmake"` solves that, as CMake then reads ${HIP_PATH}/cmake/FindHIP.cmake which does not reference amd_comgr.
It seems similar, if not the same, as I had with rocRAND [https://github.com/ROCmSoftwarePlatform/rocRAND/issues/196]()
Then, executing `make` fails with several compiler errors. branch rocm-4.2.x has similar error, but `make` is fine.

CMake-ing hipFFT (current develop branch) using just `cmake -DBUILD_WITH_LIB=CUDA ..` yields almost the same error as above. Again, using `-DCMAKE_MODULE_PATH="${HIP_PATH}/cmake"` solves that. `make` and `make install` are then fine.

but these errors seem not to be related to the `HIP_PATH` variable.


PS: I would like to suggest unifying the options USE_CUDA, BUILD_CUDA, BUILD_WITH_LIB=CUDA, etc. across the hip* libraries, and maybe set its default depending on HIP_PLATFORM environment variable.

**Comment by cgmb** [comment]
It sounds like there's a number of different ways in which the hip* library builds could be better standardized. Coordinating improvements will take some time.

For now, I've just submitted a PR to narrowly fix the issue you described in hipSOLVER.
